export const Path = {
  OrderableList: '/testOL',
  Dashboard: '/(index.html)?',
  Settings: '/settings',
  Credits: '/settings/credits',
  Gratitudes: '/gratitudes',
  NewGratitude: '/gratitudes/new',
  EditGratitude: '/gratitudes/:id/edit',
  Priorities: '/priorities',
  NewPriority: '/priorities/new',
  EditPriority: '/priorities/:id/edit',
  Relationships: '/relationships',
  NewRelationship: '/relationships/new',
  EditRelationship: '/relationships/:id/edit',
  TodaysTasks: '/tasks/today',
  Tasks: '/priority/:priority_id/project/:project_id/tasks',
  NewTask: '/priority/:priority_id/project/:project_id/tasks/new',
  EditTask: '/tasks/:id/edit',
  EditTodays: '/todays/:id/edit',
  Projects: '/priority/:priority_id/projects',
  NewProject: '/priority/:priority_id/projects/new',
  EditProject: '/projects/:id/edit',
  Contacts: '/relationship/:relationship_id/contacts',
  NewContact: '/relationship/:relationship_id/contacts/new',
  EditContact: '/contacts/:id/edit',
};
